### ISSUE TITLE
TypeError: BroccoliMergeFiles is not a constructor

### ISSUE THREAD

**Issue by noslouch** [buschtoens/broccoli-merge-files#22]
Here'a a screenshot of the simplest use case:
![image](https://user-images.githubusercontent.com/2090382/52871314-ca53a900-3117-11e9-94eb-7658db2985c4.png)

I can see in your `index.ts` that the default export is the class, but it looks like the compiled JS is missing a `module.exports = BroccoliMergeFiles` statement. Otherwise it requires node importers to do:
```node
const BroccoliMergeFiles = require('broccoli-merge-files').default;
```

I don't know typescript super well, otherwise I'd open a PR.

**Comment by buschtoens** [comment]
Thanks for reporting! I stumbles over this myself and then just went with it and forgot to fix it. Haha. 
I'll get to it in the next days.

**Comment by buschtoens** [comment]
Thanks again for reporting. Unfortunately, there is no easy way to keep the default export while also keeping TypeScript and regular CommonJS module compatibility. Hence I've just removed the default export, which also seems to be an emerging best practice.

I've released the fix as [`v0.8.0`](https://github.com/buschtoens/broccoli-merge-files/releases/tag/v0.8.0).

**Comment by noslouch** [comment]
works for me! where are you seeing not using default exports as a best practice, out of curiosity.

**Comment by buschtoens** [comment]
["`export default` considered harmful"](https://basarat.gitbooks.io/typescript/docs/tips/defaultIsBad.html) from the excellent [TypeScript Deep Dive](https://basarat.gitbooks.io/typescript/) lists pretty much all key arguments. Other than that, the general sentiment on Twitter (at least in my bubble) seems to be against default exports lately. There's also further blog posts you can find via Google. :)
